version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven dependencies"
  build:
    commands:
      - echo "Building WAR..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.war
  discard-paths: yes
